FROM nginx:alpine

ENV PRUEBA=1
ENV APP_PROFILE ""
ENV DB_URL ""
ENV DB_USER ""
ENV DB_PWD ""
ENV DB_SCHEMA ""
ENV AUTH_KEYWORD ""
ENV TOKEN_KEY=""
ENV APP_OPTS ""
ENV TZ "America/Argentina/Buenos_Aires"

ENTRYPOINT ["nginx", "-g", "daemon off;"]
