configMapGenerator:
- name: nginx-index
  files:
  - index.html
- name: nginx-config
  files:
  - default.conf

bases:
- ../base

resources:
- svc.yaml

patchesStrategicMerge:
- resources.yaml
- image.yaml
